plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'bin.mg.editor.rendering'
    compileSdk 36

    defaultConfig {
        minSdk 30
        consumerProguardFiles 'consumer-rules.pro'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {
    implementation project(':editor-core')
    implementation 'androidx.annotation:annotation:1.7.1'
    implementation 'androidx.core:core-ktx:1.12.0'
}
